/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportRouteImport } from './routes/_support'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SupportChatRouteImport } from './routes/_support.chat'
import { Route as SupportMeRouteImport } from './routes/_support.me'
import { Route as SupportRecordsRouteImport } from './routes/_support.records'
import { Route as SupportResourcesRouteImport } from './routes/_support.resources'
import { Route as SupportChatIndexRouteImport } from './routes/_support.chat.index'
import { Route as SupportChatSessionIdRouteImport } from './routes/_support.chat.$sessionId'
import { Route as SupportMePrivacyRouteImport } from './routes/_support.me.privacy'
import { Route as SupportMeSupportCardRouteImport } from './routes/_support.me_.support-card'
import { Route as SupportRecordsIndexRouteImport } from './routes/_support.records.index'
import { Route as SupportRecordsSleepRouteImport } from './routes/_support.records.sleep'
import { Route as SupportResourcesIndexRouteImport } from './routes/_support.resources.index'
import { Route as SupportResourcesExercisesExerciseIdRouteImport } from './routes/_support.resources.exercises.$exerciseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/_support',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportChatRoute = SupportChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SupportRoute,
} as any)
const SupportMeRoute = SupportMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => SupportRoute,
} as any)
const SupportRecordsRoute = SupportRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => SupportRoute,
} as any)
const SupportResourcesRoute = SupportResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => SupportRoute,
} as any)
const SupportChatIndexRoute = SupportChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportChatRoute,
} as any)
const SupportChatSessionIdRoute = SupportChatSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => SupportChatRoute,
} as any)
const SupportMePrivacyRoute = SupportMePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SupportMeRoute,
} as any)
const SupportMeSupportCardRoute = SupportMeSupportCardRouteImport.update({
  id: '/me_/support-card',
  path: '/me/support-card',
  getParentRoute: () => SupportRoute,
} as any)
const SupportRecordsIndexRoute = SupportRecordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportRecordsRoute,
} as any)
const SupportRecordsSleepRoute = SupportRecordsSleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => SupportRecordsRoute,
} as any)
const SupportResourcesIndexRoute = SupportResourcesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupportResourcesRoute,
} as any)
const SupportResourcesExercisesExerciseIdRoute =
  SupportResourcesExercisesExerciseIdRouteImport.update({
    id: '/exercises/$exerciseId',
    path: '/exercises/$exerciseId',
    getParentRoute: () => SupportResourcesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/chat': typeof SupportChatRouteWithChildren
  '/me': typeof SupportMeRouteWithChildren
  '/records': typeof SupportRecordsRouteWithChildren
  '/resources': typeof SupportResourcesRouteWithChildren
  '/chat/$sessionId': typeof SupportChatSessionIdRoute
  '/me/privacy': typeof SupportMePrivacyRoute
  '/me/support-card': typeof SupportMeSupportCardRoute
  '/records/sleep': typeof SupportRecordsSleepRoute
  '/chat/': typeof SupportChatIndexRoute
  '/records/': typeof SupportRecordsIndexRoute
  '/resources/': typeof SupportResourcesIndexRoute
  '/resources/exercises/$exerciseId': typeof SupportResourcesExercisesExerciseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/me': typeof SupportMeRouteWithChildren
  '/chat/$sessionId': typeof SupportChatSessionIdRoute
  '/me/privacy': typeof SupportMePrivacyRoute
  '/me/support-card': typeof SupportMeSupportCardRoute
  '/records/sleep': typeof SupportRecordsSleepRoute
  '/chat': typeof SupportChatIndexRoute
  '/records': typeof SupportRecordsIndexRoute
  '/resources': typeof SupportResourcesIndexRoute
  '/resources/exercises/$exerciseId': typeof SupportResourcesExercisesExerciseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_support': typeof SupportRouteWithChildren
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_support/chat': typeof SupportChatRouteWithChildren
  '/_support/me': typeof SupportMeRouteWithChildren
  '/_support/records': typeof SupportRecordsRouteWithChildren
  '/_support/resources': typeof SupportResourcesRouteWithChildren
  '/_support/chat/$sessionId': typeof SupportChatSessionIdRoute
  '/_support/me/privacy': typeof SupportMePrivacyRoute
  '/_support/me_/support-card': typeof SupportMeSupportCardRoute
  '/_support/records/sleep': typeof SupportRecordsSleepRoute
  '/_support/chat/': typeof SupportChatIndexRoute
  '/_support/records/': typeof SupportRecordsIndexRoute
  '/_support/resources/': typeof SupportResourcesIndexRoute
  '/_support/resources/exercises/$exerciseId': typeof SupportResourcesExercisesExerciseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/login'
    | '/register'
    | '/chat'
    | '/me'
    | '/records'
    | '/resources'
    | '/chat/$sessionId'
    | '/me/privacy'
    | '/me/support-card'
    | '/records/sleep'
    | '/chat/'
    | '/records/'
    | '/resources/'
    | '/resources/exercises/$exerciseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/login'
    | '/register'
    | '/me'
    | '/chat/$sessionId'
    | '/me/privacy'
    | '/me/support-card'
    | '/records/sleep'
    | '/chat'
    | '/records'
    | '/resources'
    | '/resources/exercises/$exerciseId'
  id:
    | '__root__'
    | '/'
    | '/_support'
    | '/health'
    | '/login'
    | '/register'
    | '/_support/chat'
    | '/_support/me'
    | '/_support/records'
    | '/_support/resources'
    | '/_support/chat/$sessionId'
    | '/_support/me/privacy'
    | '/_support/me_/support-card'
    | '/_support/records/sleep'
    | '/_support/chat/'
    | '/_support/records/'
    | '/_support/resources/'
    | '/_support/resources/exercises/$exerciseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SupportRoute: typeof SupportRouteWithChildren
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_support': {
      id: '/_support'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_support/chat': {
      id: '/_support/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof SupportChatRouteImport
      parentRoute: typeof SupportRoute
    }
    '/_support/me': {
      id: '/_support/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof SupportMeRouteImport
      parentRoute: typeof SupportRoute
    }
    '/_support/records': {
      id: '/_support/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof SupportRecordsRouteImport
      parentRoute: typeof SupportRoute
    }
    '/_support/resources': {
      id: '/_support/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof SupportResourcesRouteImport
      parentRoute: typeof SupportRoute
    }
    '/_support/chat/': {
      id: '/_support/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof SupportChatIndexRouteImport
      parentRoute: typeof SupportChatRoute
    }
    '/_support/chat/$sessionId': {
      id: '/_support/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof SupportChatSessionIdRouteImport
      parentRoute: typeof SupportChatRoute
    }
    '/_support/me/privacy': {
      id: '/_support/me/privacy'
      path: '/privacy'
      fullPath: '/me/privacy'
      preLoaderRoute: typeof SupportMePrivacyRouteImport
      parentRoute: typeof SupportMeRoute
    }
    '/_support/me_/support-card': {
      id: '/_support/me_/support-card'
      path: '/me/support-card'
      fullPath: '/me/support-card'
      preLoaderRoute: typeof SupportMeSupportCardRouteImport
      parentRoute: typeof SupportRoute
    }
    '/_support/records/': {
      id: '/_support/records/'
      path: '/'
      fullPath: '/records/'
      preLoaderRoute: typeof SupportRecordsIndexRouteImport
      parentRoute: typeof SupportRecordsRoute
    }
    '/_support/records/sleep': {
      id: '/_support/records/sleep'
      path: '/sleep'
      fullPath: '/records/sleep'
      preLoaderRoute: typeof SupportRecordsSleepRouteImport
      parentRoute: typeof SupportRecordsRoute
    }
    '/_support/resources/': {
      id: '/_support/resources/'
      path: '/'
      fullPath: '/resources/'
      preLoaderRoute: typeof SupportResourcesIndexRouteImport
      parentRoute: typeof SupportResourcesRoute
    }
    '/_support/resources/exercises/$exerciseId': {
      id: '/_support/resources/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/resources/exercises/$exerciseId'
      preLoaderRoute: typeof SupportResourcesExercisesExerciseIdRouteImport
      parentRoute: typeof SupportResourcesRoute
    }
  }
}

interface SupportChatRouteChildren {
  SupportChatSessionIdRoute: typeof SupportChatSessionIdRoute
  SupportChatIndexRoute: typeof SupportChatIndexRoute
}

const SupportChatRouteChildren: SupportChatRouteChildren = {
  SupportChatSessionIdRoute: SupportChatSessionIdRoute,
  SupportChatIndexRoute: SupportChatIndexRoute,
}

const SupportChatRouteWithChildren = SupportChatRoute._addFileChildren(
  SupportChatRouteChildren,
)

interface SupportMeRouteChildren {
  SupportMePrivacyRoute: typeof SupportMePrivacyRoute
}

const SupportMeRouteChildren: SupportMeRouteChildren = {
  SupportMePrivacyRoute: SupportMePrivacyRoute,
}

const SupportMeRouteWithChildren = SupportMeRoute._addFileChildren(
  SupportMeRouteChildren,
)

interface SupportRecordsRouteChildren {
  SupportRecordsSleepRoute: typeof SupportRecordsSleepRoute
  SupportRecordsIndexRoute: typeof SupportRecordsIndexRoute
}

const SupportRecordsRouteChildren: SupportRecordsRouteChildren = {
  SupportRecordsSleepRoute: SupportRecordsSleepRoute,
  SupportRecordsIndexRoute: SupportRecordsIndexRoute,
}

const SupportRecordsRouteWithChildren = SupportRecordsRoute._addFileChildren(
  SupportRecordsRouteChildren,
)

interface SupportResourcesRouteChildren {
  SupportResourcesIndexRoute: typeof SupportResourcesIndexRoute
  SupportResourcesExercisesExerciseIdRoute: typeof SupportResourcesExercisesExerciseIdRoute
}

const SupportResourcesRouteChildren: SupportResourcesRouteChildren = {
  SupportResourcesIndexRoute: SupportResourcesIndexRoute,
  SupportResourcesExercisesExerciseIdRoute:
    SupportResourcesExercisesExerciseIdRoute,
}

const SupportResourcesRouteWithChildren =
  SupportResourcesRoute._addFileChildren(SupportResourcesRouteChildren)

interface SupportRouteChildren {
  SupportChatRoute: typeof SupportChatRouteWithChildren
  SupportMeRoute: typeof SupportMeRouteWithChildren
  SupportRecordsRoute: typeof SupportRecordsRouteWithChildren
  SupportResourcesRoute: typeof SupportResourcesRouteWithChildren
  SupportMeSupportCardRoute: typeof SupportMeSupportCardRoute
}

const SupportRouteChildren: SupportRouteChildren = {
  SupportChatRoute: SupportChatRouteWithChildren,
  SupportMeRoute: SupportMeRouteWithChildren,
  SupportRecordsRoute: SupportRecordsRouteWithChildren,
  SupportResourcesRoute: SupportResourcesRouteWithChildren,
  SupportMeSupportCardRoute: SupportMeSupportCardRoute,
}

const SupportRouteWithChildren =
  SupportRoute._addFileChildren(SupportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SupportRoute: SupportRouteWithChildren,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
