"""S2 STEP04 canonical memory

Revision ID: n014_memory
Revises: m013_background_jobs
Create Date: 2026-10-02 11:16:03.053752

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "n014_memory"
down_revision: str | Sequence[str] | None = "m013_background_jobs"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_grant_owner", "context_grants", ["id", "owner_id"])
    for table, column, values in (
        (
            "context_grants",
            "source_type",
            "'conversation','message','note','sleep_record','support_card'",
        ),
        (
            "deletion_jobs",
            "target_type",
            "'conversation','note','sleep_record','support_card','memory'",
        ),
    ):
        for constraint in sa.inspect(op.get_bind()).get_check_constraints(table):
            if column in constraint["sqltext"]:
                op.drop_constraint(constraint["name"], table, type_="check")
        op.create_check_constraint("ck_" + table + "_types", table, column + " IN (" + values + ")")
    op.create_table(
        "memories",
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("claim_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column("correction_id", sa.String(length=36), nullable=True),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("retention_policy_id", sa.String(length=80), nullable=False),
        sa.Column("source_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("consent_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "claim_type IN ('user_statement','user_feeling',"
            "'system_inference','confirmed_preference')"
        ),
        sa.CheckConstraint("status IN ('active','needs_review','stopped','deleted')"),
        sa.CheckConstraint("version > 0"),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_id"),
    )
    op.create_index(op.f("ix_memories_owner_id"), "memories", ["owner_id"], unique=False)
    op.create_table(
        "memory_suppressions",
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("reason", sa.String(length=30), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("retention_policy_id", sa.String(length=80), nullable=False),
        sa.Column("source_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("consent_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "source_key"),
    )
    op.create_index(
        op.f("ix_memory_suppressions_owner_id"), "memory_suppressions", ["owner_id"], unique=False
    )
    op.create_table(
        "memory_candidates",
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("memory_id", sa.String(length=36), nullable=True),
        sa.Column("proposed_content", sa.Text(), nullable=False),
        sa.Column("claim_type", sa.String(length=30), nullable=False),
        sa.Column("operation", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("generator_version", sa.String(length=100), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("retention_policy_id", sa.String(length=80), nullable=False),
        sa.Column("source_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("consent_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("operation = 'insert'"),
        sa.CheckConstraint("status IN ('saved','invalidated','deleted')"),
        sa.ForeignKeyConstraint(
            ["job_id", "owner_id"],
            ["background_jobs.id", "background_jobs.owner_id"],
        ),
        sa.ForeignKeyConstraint(
            ["memory_id", "owner_id"],
            ["memories.id", "memories.owner_id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_id"),
        sa.UniqueConstraint("job_id", "ordinal"),
    )
    op.create_index(
        op.f("ix_memory_candidates_owner_id"), "memory_candidates", ["owner_id"], unique=False
    )
    op.create_table(
        "artifact_sources",
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("grant_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("grant_version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["grant_id", "owner_id"],
            ["context_grants.id", "context_grants.owner_id"],
        ),
        sa.ForeignKeyConstraint(
            ["memory_id", "owner_id"],
            ["memories.id", "memories.owner_id"],
        ),
        sa.PrimaryKeyConstraint("memory_id", "grant_id"),
    )
    op.create_index(
        op.f("ix_artifact_sources_owner_id"), "artifact_sources", ["owner_id"], unique=False
    )
    op.add_column(
        "background_jobs",
        sa.Column(
            "provider_profile",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
    )
    op.add_column("background_jobs", sa.Column("encrypted_config", sa.Text(), nullable=True))
    op.add_column(
        "context_grants",
        sa.Column(
            "message_source_id",
            sa.String(length=36),
            sa.Computed(
                "CASE WHEN source_type = 'message' THEN source_id END",
            ),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_grant_message_owner",
        "context_grants",
        "messages",
        ["message_source_id", "owner_id"],
        ["id", "owner_id"],
    )
    op.add_column(
        "deletion_jobs",
        sa.Column(
            "memory_target_id",
            sa.String(length=36),
            sa.Computed(
                "CASE WHEN target_type = 'memory' THEN target END",
            ),
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "fk_deletion_memory_owner",
        "deletion_jobs",
        "memories",
        ["memory_target_id", "owner_id"],
        ["id", "owner_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().scalar(
        sa.text("SELECT EXISTS (SELECT 1 FROM background_jobs WHERE kind = 'memory_extraction')")
    ):
        raise RuntimeError("Memory job receipts exist; destructive downgrade refused")
    for table in ("memories", "memory_candidates", "memory_suppressions"):
        if op.get_bind().scalar(sa.text(f"SELECT EXISTS (SELECT 1 FROM {table})")):
            raise RuntimeError("Memory receipts exist; destructive downgrade refused")
    if op.get_bind().scalar(
        sa.text("SELECT EXISTS (SELECT 1 FROM context_grants WHERE source_type = 'message')")
    ):
        raise RuntimeError("Message grants exist; destructive downgrade refused")
    op.drop_table("artifact_sources")
    op.drop_table("memory_candidates")
    op.drop_constraint("fk_deletion_memory_owner", "deletion_jobs", type_="foreignkey")
    op.drop_column("deletion_jobs", "memory_target_id")
    op.drop_constraint("fk_grant_message_owner", "context_grants", type_="foreignkey")
    op.drop_constraint("uq_grant_owner", "context_grants", type_="unique")
    op.drop_column("context_grants", "message_source_id")
    op.drop_column("background_jobs", "encrypted_config")
    op.drop_column("background_jobs", "provider_profile")
    op.drop_table("memory_suppressions")
    op.drop_table("memories")
    for table, column in (("context_grants", "source_type"), ("deletion_jobs", "target_type")):
        op.drop_constraint("ck_" + table + "_types", table, type_="check")
        op.create_check_constraint(
            "ck_" + table + "_typed",
            table,
            column + " IN ('conversation','note','sleep_record','support_card')",
        )
